### ISSUE TITLE
usage of model.enable_input_require_grads()

### ISSUE THREAD

**Issue by gengyuanmax** [yukw777/EILEV#12]
Hi, thanks for your work!

I have a question about `model.enable_input_require_grads()` in train_v2.py. With this line, you intend to unfreeze the input embeddings of LLMs. Does it have a big impact on the performance?

Best,

**Comment by yukw777** [comment]
`enable_input_require_grads()` doesn't unfreeze the embeddings. Rather, it enables gradient tracking on the "output" of the embedding layer. (https://github.com/huggingface/transformers/blob/09f9f566de83eef1f13ee83b5a1bbeebde5c80c1/src/transformers/modeling_utils.py#L1563). This allows the training of the Q-Former. Without it, you're essentially running the model in eval mode.
