### ISSUE TITLE
Sampling in-context demo for evaluation

### ISSUE THREAD

**Issue by gengyuanmax** [yukw777/EILEV#15]
Thanks for the work.

I have a question about how to sample in-context demo for evaluation. I coulnd't find the script to generate the 'in_context_query_map_file'. How do you implement this part? If you sample the demo samples based on the structured verbs and nouns as training, do you use the ground truth label in the annotation?

Thanks for your reply.

**Comment by yukw777** [comment]
Hi there! Here's the script that generates the mapping file: https://github.com/yukw777/EILEV/blob/main/scripts/general/sample_in_context_examples.py

And yes, we do use the ground truth labels provided by Ego4D.
