### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by fazlicodes** [yukw777/EILEV#2]
I getting the following error:
`OSError: kpyu/eilev-blip2-opt-2.7b does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.`
when I ran:
`python demo/eilev_demo.py --device cuda`

**Comment by fazlicodes** [comment]
Thanks, I updated and Iwas able to run the demo, but it doesn't return to my query on a 41 second video

**Comment by yukw777** [comment]
Please open up another issue for it with more details so that I can track things easier. I'll close this issue as the initial issue has been resolved. Please note that the demo only processes the first 8 seconds of the video by default as mentioned in the limitations section.
