### ISSUE TITLE
ELLEV vs Video BLIP2

### ISSUE THREAD

**Issue by gordonhu608** [yukw777/EILEV#3]
Thanks for your great work. After reading the paper, I'm still a little bit confusing about the difference between ELLEV and Video BLIP2. Is video BLIP2 also trained using interleaved text and image frame? Any other difference? Thank you.

**Comment by yukw777** [comment]
Hi @gordonhu608! The following quote from README.md might be of help:

> It is an extension to the preliminary work done in [VideoBLIP](https://github.com/yukw777/VideoBLIP), which contains models trained using EILEV with no in-context examples.

Essentially, VideoBLIP is a set of models that have been trained using a special case of EILEV where no in-context examples are provided during training, i.e., just a pair consisting of text and a set of frames. In contrast, the released EILEV-trained models have been trained with 16 in-context examples and a query.

Please let me know if you have more questions, or have any suggestions on how to make this clearer on README.md.
