### ISSUE TITLE
Training memory 

### ISSUE THREAD

**Issue by gordonhu608** [yukw777/EILEV#4]
As you mentioned EILEV-trained models have been trained with 16 in-context examples and a query. So I assume there are 16 * 32 = 512 query tokens and text query concatenated together. Besides there also 16 image feature vectors encoded by ViT. I'm wondering how much memory it takes for this single batch in one GPU. As mentioned in your paper, global bs is 128, so I'm wondering like how many grad_iter accumulation you employed in your training setting? Thanks.

**Comment by yukw777** [comment]
These values are provided in the training section of README.md: https://github.com/yukw777/EILEV?tab=readme-ov-file#training.
