### ISSUE TITLE
Unable to Generate Text using VideoBlip Model

### ISSUE THREAD

**Issue by alexhe101** [yukw777/EILEV#9]
**Description:**
I have been following the provided script (video_blip_generate_action_narration.py) to generate text from a video using the VideoBlip model (kpyu/video-blip-flan-t5-xl-ego4d). However, despite following the instructions and providing the necessary input, the generated text appears to be empty, containing only spaces.
**Command used:**
``` 
python samples/video_blip_generate_action_narration.py \
  --device cuda \
  demo/examples/bike-fixing-0.mp4 \
  "What is the camera wearer doing?"
```
Expected Behavior: The script should generate meaningful text describing the action in the provided video.
Actual Behavior: The generated text is empty, consisting only of spaces.

**Comment by yukw777** [comment]
I can't reproduce the issue on my machine:

```
python samples/video_blip_generate_action_narration.py \
  --device cuda \
  demo/examples/bike-fixing-0.mp4 \
  "What is the camera wearer doing?"
[2024-02-27 00:08:25,823] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.05s/it]
Generated_text: he is working on his bike
```

I'd need more information so that I can reproduce the issue. Maybe you have installed some custom libraries that may change the behavior? Could you try again with a fresh virtualenv?

**Comment by alexhe101** [comment]
> I can't reproduce the issue on my machine:
> 
> ```
> python samples/video_blip_generate_action_narration.py \
>   --device cuda \
>   demo/examples/bike-fixing-0.mp4 \
>   "What is the camera wearer doing?"
> [2024-02-27 00:08:25,823] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.05s/it]
> Generated_text: he is working on his bike
> ```
> 
> I'd need more information so that I can reproduce the issue. Maybe you have installed some custom libraries that may change the behavior? Could you try again with a fresh virtualenv?
thank you for his reply. I have solved the problem. I found that when the input prompt becomes "question: xxxx? answer:", the model can work normally.

**Comment by yukw777** [comment]
> thank you for his reply. I have solved the problem. I found that when the input prompt becomes "question: xxxx? answer:", the model can work normally.

Just for posterity, you shouldn't have to format your prompt like that with Flan-backed models, e.g., `kpyu/video-blip-flan-t5-xl-ego4d`, as they're already instruction-tuned. You can see in my previous reply that I get the correct behavior without having to format my prompt that way. I'm not sure why that's not working for you.
